services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=todo
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres: